name: Build Enmity and Inject Rosiecord
on:
  workflow_dispatch:
    inputs:
      discord_link:
        description: 'Discord link to download'
        required: true
        type: string



jobs:
  build:
    name: Build Enmity and Inject Rosiecord
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          node-version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'latest'
      - name: Ensure main utils are installed
        id: core
        run: brew install coreutils ldid
      - name: build scripts
        id: build
        run: |
          pnpm install
          pnpm run build
      - name: Run Main Node Script to Patch Rosiecord
        id: build
        run: node ./index.js --discord-link ${{ github.event.inputs.discord_link }}
        
      - name: Retrieve version
        id: version
        run: |
          cd ./ipas
          echo "__DISCORD_VERSION=$(ls | grep Discord | sed -e s/[^0-9.]//g | sed -e s/[/.+?\./]//g)" >> $GITHUB_OUTPUT  

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: rosiecord_${{ steps.version.outputs.__DISCORD_VERSION }}
          title: Rosiecord ${{ steps.version.outputs.__DISCORD_VERSION }}
          files: Dist/*.ipa
